### ISSUE TITLE
AVIM fails to ignore readonly form fields

### ISSUE THREAD

**Issue by 1ec5** [kimkha/avim-chrome#15]
If you place the insertion point after the “d” in this textarea and press <kbd>D</kbd>:

```html
<textarea readonly>d</textarea>
```

AVIM changes the “d” to a “đ”. This is problematic because you still mostly can’t type into the field, and you can’t remove the errant text either.

Also reproduces in Google Input Tools, as well as AVIM (1ec5/avim#163), Mudim, and Typing Vietnamese in Firefox.

**Comment by 1ec5** [comment]
[Fixed in avim.js](http://vi.wikipedia.org/wiki/Đặc_biệt:Khác/22654885).

**Comment by kimkha** [comment]
Thank you!
