### ISSUE TITLE
Không gõ được tiếng việt trên address bar

### ISSUE THREAD

**Issue by johnsmeeth** [kimkha/avim-chrome#19]
Như tiêu đề đang cài cái này trên yandex browser không gõ đc tiếng việt trên address bar chỉ gõ đc trên các input control trên page

**Comment by 1ec5** [comment]
Đáng tiếc, đây là một hạn chế của hệ thống tiện ích của các trình duyệt Chromium như Chrome, Yandex, Opera, Cốc Cốc…: các tiện ích chỉ có thể gắn vào nội dung trang Web. Chỉ có Firefox cho phép tiện ích gắn vào toàn bộ giao diện, thí dụ thanh địa chỉ. Nếu bạn cần tính năng này thì hãy thử [AVIM cho Firefox](http://avim.1ec5.org/).
