### ISSUE TITLE
Hỗ trợ Opera

### ISSUE THREAD

**Issue by 1ec5** [kimkha/avim-chrome#9]
Opera 15+ có cùng nền tiện ích với Google Chrome và hỗ trợ nhiều API `chrome.*`. Xem [tài liệu](https://dev.opera.com/extensions/). Chắc avim-chrome sẽ hoạt động tốt trong Opera. Xin kiểm tra và tải lên [kho tiện ích Opera](https://addons.opera.com/vi/extensions/) nếu được.

**Comment by kimkha** [comment]
Mấy hôm nay bận làm dự án khác nên chưa coi thêm được... Để mình thử đưa lên đó xem.

**Comment by kimkha** [comment]
Now, it support Opera: https://addons.opera.com/extensions/details/avim-vietnamese-input-method/

**Comment by 1ec5** [comment]
Cám ơn bạn!
